In [3]:
import numpy as np

In [5]:
# 1. Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

random_array = np.random.randint(0,50, size=(10, 10))
random_array

array([[ 2, 11, 41, 41, 44,  9, 20, 29, 44,  6],
       [33, 38, 38,  5, 26, 43, 26,  4, 42, 47],
       [ 0,  4, 47, 13,  7, 23,  8, 37, 23,  2],
       [43, 36, 18, 39,  6,  4, 10,  8, 15,  5],
       [22, 36, 42, 13, 10, 45, 24, 12, 36, 20],
       [42,  4, 28, 12, 19, 41, 26, 15, 26,  6],
       [13, 18,  9, 34,  0, 19, 40,  3, 42, 25],
       [ 1, 39,  6, 42, 32, 15, 41, 27, 17, 10],
       [44, 14, 24,  8, 34, 23, 25, 47, 27, 35],
       [38,  2,  4, 11, 16, 43, 18, 12,  8, 10]])

In [ ]:
np.where((3 < random_array) & (random_array < 8), -1*random_array, random_array)

array([[38, -6, 49, 21, 12, 20, -6, 29, 30, 38],
       [15, 12, 47, 46, 31, 17, 10, 42, 37, 21],
       [-6, 37, 27, -6, 18, 25, 43, 37, 44, 38],
       [20, 16, 18, 36, 17, 14, -7, 20, 37, 38],
       [14, 12,  0, 10, 14, 25,  2, 16, 32, 14],
       [ 2, 32, 11,  1, 41, 17, 15, 46, 28, 10],
       [40, 43, 48, 31, 31, 20, 41, 11, 38, -4],
       [49, 11, 49, 36, 37, 17, 38, 19, 21, -7],
       [27, 25, 47, 32, 42, 47, 35, 10, 15, 38],
       [25, 12, -6, 33,  1, 12, 30, 38, 32, 22]])

In [ ]:
# 2. Заменить максимальный элемент случайного массива на 0

max_index = np.unravel_index(np.argmax(random_array), random_array.shape)
random_array[max_index] = 0
random_array

array([[10, 23,  9, 18,  0, 19, 30,  1,  2,  5],
       [17, 18, 10, 23, 38,  3, 24, 22, 13, 27],
       [28, 25, 26, 41,  9,  7, 33, 37, 18, 14],
       [ 7,  5,  8, 40, 32, 16,  9, 20, 35, 27],
       [27,  0, 24, 15,  6, 29,  6, 22, 34, 43],
       [43, 17,  5, 44, 21,  0, 48, 15, 28, 39],
       [23, 37, 44, 41,  3, 24, 33, 20,  8, 31],
       [ 1,  1, 21, 33, 47, 34,  3, 20, 41, 43],
       [ 3, 39,  0,  2, 41, 24, 33, 43, 19, 45],
       [23,  3, 16, 39, 43,  5,  2,  6, 14, 10]])

In [ ]:
# 3. Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив.
array_2d = np.array([[1, 2, 3, 4, 5],
                     [6, 7, 8, 9, 10]])

# Compute the Cartesian product
cartesian_product = np.transpose([np.tile(array_2d[0], len(array_2d[1])),
                                  np.repeat(array_2d[1], len(array_2d[0]))])

print("Cartesian Product:")
print(cartesian_product)



Cartesian Product:
[[ 1  6]
 [ 2  6]
 [ 3  6]
 [ 4  6]
 [ 5  6]
 [ 1  7]
 [ 2  7]
 [ 3  7]
 [ 4  7]
 [ 5  7]
 [ 1  8]
 [ 2  8]
 [ 3  8]
 [ 4  8]
 [ 5  8]
 [ 1  9]
 [ 2  9]
 [ 3  9]
 [ 4  9]
 [ 5  9]
 [ 1 10]
 [ 2 10]
 [ 3 10]
 [ 4 10]
 [ 5 10]]


In [ ]:
# 4. Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат
# элементы из каждой строки в B, независимо от порядка элементов в B

A = np.random.randint(0, 6, size=(8, 3))
B = np.random.randint(0, 6, size=(2, 2))
print(A)
print()
print()
print(B)
print()

for row in A:
    if np.all(np.isin(row, B)):
        print(f"Строки A, элементы которых полностью есть в B:")
        print(row)

[[5 2 5]
 [5 5 0]
 [5 5 5]
 [3 1 3]
 [0 2 0]
 [0 0 0]
 [4 5 1]
 [5 0 2]]


[[3 3]
 [4 5]]

Строки A, элементы которых полностью есть в B:
[5 5 5]


In [ ]:
# 5. Дана 10x3 матрица, найти строки из неравных значений
# (например строка [2,2,3] остается, строка [3,3,3] удаляется)

fifth_matrix = np.random.randint(0,3, size=(10, 3))
print("Given matrix:")
print(fifth_matrix)


def all_elements_same(array):
    # Convert the list of arrays to a 2D Numpy array
    arr = np.array(array)

    # Check if all elements in each row are equal to the first element
    return (arr == arr[:, 0, None]).all(axis=1)

result = all_elements_same(fifth_matrix)
print()
print("Rows with not equal elements:")
for row_idx, is_same in enumerate(result):
    if not is_same:
        print(f"Row {row_idx}: {fifth_matrix[row_idx]}")

print()

print("Rows with the same elements, that were deleted:")
for row_idx, is_same in enumerate(result):
    if is_same:
        print(f"Row {row_idx}: {fifth_matrix[row_idx]}")

Given matrix:
[[1 2 1]
 [0 1 2]
 [2 0 2]
 [0 2 2]
 [1 0 1]
 [1 1 0]
 [0 0 0]
 [1 1 1]
 [1 2 1]
 [1 2 0]]

Rows with not equal elements:
Row 0: [1 2 1]
Row 1: [0 1 2]
Row 2: [2 0 2]
Row 3: [0 2 2]
Row 4: [1 0 1]
Row 5: [1 1 0]
Row 8: [1 2 1]
Row 9: [1 2 0]

Rows with the same elements, that were deleted:
Row 6: [0 0 0]
Row 7: [1 1 1]


In [ ]:
# 6. Дан двумерный массив. Удалить те строки, которые повторяются.

sixth_arr = np.random.randint(0,4, size=(20, 3))
print("The initial 2-d array:")
print()
print(sixth_arr)
print()
print(f"The amount of rows:", sixth_arr.shape[0])

print()
print()
print("The array with only unique values:")
unique_rows = np.unique(sixth_arr, axis = 0)
print(unique_rows)
print()
print(f"The amount of rows:", unique_rows.shape[0])
print()
print(f"{sixth_arr.shape[0]-unique_rows.shape[0]} rows were not unique and, therefore, deleted.")

The initial 2-d array:

[[0 2 2]
 [1 3 3]
 [2 1 0]
 [2 0 1]
 [1 0 2]
 [2 1 2]
 [0 1 2]
 [0 0 1]
 [2 0 3]
 [3 0 1]
 [3 3 2]
 [0 1 0]
 [2 2 2]
 [1 2 3]
 [1 0 2]
 [2 1 1]
 [1 3 2]
 [3 1 3]
 [2 1 1]
 [0 2 1]]

The amount of rows: 20


The array with only unique values:
[[0 0 1]
 [0 1 0]
 [0 1 2]
 [0 2 1]
 [0 2 2]
 [1 0 2]
 [1 2 3]
 [1 3 2]
 [1 3 3]
 [2 0 1]
 [2 0 3]
 [2 1 0]
 [2 1 1]
 [2 1 2]
 [2 2 2]
 [3 0 1]
 [3 1 3]
 [3 3 2]]

The amount of rows: 18

2 rows were not unique and, therefore, deleted.


In [17]:
#######################################################################################
# Tasks pure Python v.s. Numpy

In [ ]:
# Задача 1. Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.
# Например, для X = np.array([ [1, 0, 1],
#                              [2, 0, 2],
#                              [3, 0, 3],
#                              [4, 4, 4]]) ответ 3.

# Numpy solution

rand_array = np.random.randint(0,7, size=(4, 6))
print(rand_array)

print()
not_null_values_multiplicated = 1
diagonal_values = np.diagonal(rand_array)
print(f"The values on a diagonal: {diagonal_values}")
for value in diagonal_values:
  if value != 0:
    not_null_values_multiplicated = not_null_values_multiplicated * value
print(f"The product of these values: {not_null_values_multiplicated}")

[[4 2 4 0 0 5]
 [0 6 6 3 3 5]
 [0 4 2 4 1 0]
 [4 6 5 5 6 0]]

The values on a diagonal: [4 6 2 5]
The product of these values: 240


In [ ]:
# Pure Python solution

from random import randint

print("The given matrix:")
matrix=[]
for i in range(4):
    line=[]
    for j in range(6):
        line.append(randint(0,5))
    matrix.append(line)
for line in matrix:
  print(line)

print()
print("The diagonal values:")
product=1
for i in range(5):
    for j in range(3):
        if i==j and matrix[i][j]!=0:
          print(matrix[i][j])
          product=product*matrix[i][j]

print()
print(f"The product of diagonal values is: {product}")

The given matrix:
[4, 5, 5, 3, 4, 0]
[4, 2, 5, 1, 5, 5]
[0, 5, 0, 5, 5, 5]
[4, 2, 3, 3, 1, 2]

The diagonal values:
4
2

The product of diagonal values is: 8


In [ ]:
# Задача 2: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.
# Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

# Numpy solution

x=np.random.randint(0,3,5)
print(x)
y=np.random.randint(0,3,5)
print(y)

if np.array_equal(np.sort(x), np.sort(y)):
    print("The arrays create the same multiset.")
else:
    print("The arrays do not create the same multiset.")

[2 0 2 2 1]
[1 0 1 2 0]
The arrays do not create the same multiset.


In [ ]:
# Python solution
import random

listik =[]

for i in range(5):
  random_int = random.randint(0, 3)
  listik.append(random_int)
print(listik)

listochek =[]

for i in range(5):
  random_int = random.randint(0, 3)
  listochek.append(random_int)
print(listochek)

are_equal_sorted = sorted(listik) == sorted(listochek)
if are_equal_sorted:
    print("The lists have the same elements.")
else:
    print("The lists do not have the same elements.")


[3, 0, 1, 2, 1]
[1, 0, 3, 1, 2]
The lists have the same elements.


In [ ]:
# Задача 3: Найти максимальный элемент в векторе x среди элементов,
# перед которыми стоит ноль. Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

#Python solution:
import random
x = []
for i in range (20):
    x.append(random.randint(0,4))
print(x)
print()

try:
  list_before_null = []
  for i, element in enumerate(x):
      if i > 0 and x[i - 1] == 0:
          list_before_null.append(element)
except:
  print("There is no zeros in array.")


print("The list of values that have 0 before them:")
print(list_before_null)
print()
print("The biggest value out of them:")
print(max(list_before_null))

[2, 3, 4, 1, 1, 1, 4, 4, 0, 0, 4, 4, 4, 0, 4, 3, 3, 4, 4, 1]

The list of values that have 0 before them:
[0, 4, 4]

The biggest value out of them:
4


In [ ]:
# Numpy solution

random_arry =np.random.randint(0,7,15)
print(random_arry)

values_after_zero = []

for i in range(len(random_arry) - 1):
    if random_arry[i] == 0:
        values_after_zero.append(random_arry[i + 1])

try:
    print("The largest value immediately after 0 is:", max(values_after_zero))
except:
    print("No values found immediately after 0.")


[2 4 0 6 3 3 5 0 0 1 1 3 5 2 2]
The largest value immediately after 0 is: 6


In [ ]:
# Задача 4: Реализовать кодирование длин серий (Run-length encoding).
# Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины.
# Первый содержит числа, а второй - сколько раз их нужно повторить.
# Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

# Python solution:
def run_length_encode(arr):
    values = []
    lengths = []
    current_value = arr[0]
    current_length = 1

    for i in range(1, len(arr)):
        if arr[i] == current_value:
            current_length += 1
        else:
            values.append(current_value)
            lengths.append(current_length)

            current_value = arr[i]
            current_length = 1

    values.append(current_value)
    lengths.append(current_length)

    values = np.array(values)
    lengths = np.array(lengths)

    return values, lengths

arr =np.random.randint(0,4,15)
print("Given array:", arr)
print()

encoded_values, run_lengths = run_length_encode(arr)
returned_list = (encoded_values, run_lengths)

print(returned_list)

Given array: [0 1 1 3 1 3 2 2 3 0 0 1 1 3 2]

(array([0, 1, 3, 1, 3, 2, 3, 0, 1, 3, 2]), array([1, 2, 1, 1, 1, 2, 1, 2, 2, 1, 1]))


In [ ]:
# Numpy solution:

def run_length_encoding(arr):
    diff = np.concatenate(([True], arr[1:] != arr[:-1], [True]))
    idx = np.flatnonzero(diff)

    lengths = np.diff(idx)

    values = arr[idx[:-1]]

    return values, lengths

arr =np.random.randint(0,4,15)
print(arr)
values, lengths = run_length_encoding(arr)
print("Values:", values)
print("Lengths:", lengths)


[3 2 0 2 1 1 1 2 0 1 0 2 3 2 2]
Values: [3 2 0 2 1 2 0 1 0 2 3 2]
Lengths: [1 1 1 1 3 1 1 1 1 1 1 2]


In [14]:
# Задача 5: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами.
# Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

# Numpy solution

from scipy.spatial import distance

X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Y = np.array([[2, 4, 6], [1, 3, 5]])

# Calculate Euclidean distance using NumPy
distance_matrix = np.linalg.norm(X[:, np.newaxis] - Y, axis=2)

print("Euclidean distance matrix:")
print(distance_matrix)

# Compare with scipy.spatial.distance.cdist
scipy_distance_matrix = distance.cdist(X, Y, metric='euclidean')

print("\nScipy distance matrix:")
print(scipy_distance_matrix)


Euclidean distance matrix:
[[3.74165739 2.23606798]
 [2.23606798 3.74165739]
 [7.07106781 8.77496439]]

Scipy distance matrix:
[[3.74165739 2.23606798]
 [2.23606798 3.74165739]
 [7.07106781 8.77496439]]


In [15]:
# Python solution
def euclidean_distance(a, b):
    assert len(a) == len(b), "Input vectors must have the same length"

    squared_diffs = [(x - y) ** 2 for x, y in zip(a, b)]

    distance = sum(squared_diffs) ** 0.5

    return distance

X = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]
Y = [(2, 4, 6), (1, 3, 5)]

distance_matrix = []

for x in X:
    row_distances = [euclidean_distance(x, y) for y in Y]
    distance_matrix.append(row_distances)

for row in distance_matrix:
    print(row)


[3.7416573867739413, 2.23606797749979]
[2.23606797749979, 3.7416573867739413]
[7.0710678118654755, 8.774964387392123]


In [ ]:
##################################################################################

In [7]:
# Задача 6.

# 1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий
# для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.


calorie_stats = np.loadtxt("/content/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

In [ ]:
# 2. В одной порции CrunchieMunchies содержится 60 калорий.
# Насколько выше среднее количество калорий у ваших конкурентов?
# Сохраните ответ в переменной average_calories и распечатайте переменную в терминале.

average_calories = np.round(np.average(calorie_stats))
print("The average amount of calories of competitors' products is:", average_calories)
print("It is, on average,",average_calories - 60,"calories, or,", np.round(100*(47/60)),"% higher.")


The average amount of calories of competitors' products is: 107.0
It is, on average, 47.0 calories, or, 78.0 % higher.


In [ ]:
# 3. Корректно ли среднее количество калорий отражает распределение набора данных?
# Давайте отсортируем данные и посмотрим.
# Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted.
# Распечатайте отсортированную информацию.

calorie_stats_sorted = np.sort(calorie_stats)
print("Sorted data:")
print()
calorie_stats_sorted

Sorted data:



array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

In [ ]:
# 4. Похоже, что большинство значений выше среднего. Давайте посмотрим,
# является ли медиана наиболее корректным показателем набора данных.
# Вычислите медиану набора данных и сохраните свой ответ в median_calories.
# Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

median_calories = np.median(calorie_stats)
print("Median:",median_calories)
print("Mean:",average_calories)

print()
print(calorie_stats_sorted)
print()
print("Yes, median seems to reflect the tendency more correctly.")

Median: 110.0
Mean: 107.0

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]

Yes, median seems to reflect the tendency more correctly.


In [ ]:
# 5. В то время как медиана показывает, что по крайней мере половина
# наших значений составляет более 100 калорий, было бы более впечатляюще показать,
# что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.
# Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль,
# превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

print("Percentile - 50. Calories:", np.percentile(calorie_stats, 50))
print("Percentile - 40. Calories:", np.percentile(calorie_stats, 40))
print("Percentile - 20. Calories:", np.percentile(calorie_stats, 20))
print("Percentile - 15. Calories:", np.percentile(calorie_stats, 15))
print("Percentile - 10. Calories:", np.percentile(calorie_stats, 10))
print("Percentile - 7. Calories:", np.percentile(calorie_stats, 7))
print("Percentile - 4. Calories:", np.percentile(calorie_stats, 4))
print("Percentile - 3. Calories:", np.percentile(calorie_stats, 3))
print()
print("The lowest percentile, whose value is > 60 calories, is 4.")

Percentile - 50. Calories: 110.0
Percentile - 40. Calories: 110.0
Percentile - 20. Calories: 100.0
Percentile - 15. Calories: 90.0
Percentile - 10. Calories: 90.0
Percentile - 7. Calories: 83.2
Percentile - 4. Calories: 70.0
Percentile - 3. Calories: 55.599999999999994

The lowest percentile, whose value is > 60 calories, is 4.


In [ ]:
# 6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше,
# это неудобная концепция для использования в маркетинговых материалах.
# Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию.
# Сохраните свой ответ в переменной more_calories и распечатайте его

more_than_sixty = 100 - 4
print(f"Only 4% of competitors have as little calories as our product. \
And {more_than_sixty}% of competitors have more calories than we do.")

Only 4% of competitors have as little calories as our product. And 96% of competitors have more calories than we do.


In [13]:
# 7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies.
# Но один вопрос заключается в том, насколько велики различия в наборе данных?
# Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?
# Рассчитайте величину отклонения, найдя стандартное отклонение,
# Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

std = np.std(calorie_stats)
our_deviation = (110-60)/19
print(f"The standard deviation is {std}.")
print()
print(f"It means that the majority has the range of calories from 90 to 130. But our product is {our_deviation} deviations below the average!")

The standard deviation is 19.35718533390827.

It means that the majority has the range of calories from 90 to 130. But our product is 2.6315789473684212 deviations below the average!


In [ ]:
# 8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как,
# по вашему мнению, эти данные могут быть использованы в интересах Mycrunch
# при маркетинге CrunchieMunchies.


# Практически никто на рынке не может сравниться с CrunchieMunchies по такой низкокалорийности!
# Производитель входит в 4 % самых низкокалорийных производителей. Калорийность их продукта - сильно ниже среднего.
# Это отличный point для рекламы.